#!/usr/bin/python

'''
./na add --title "oceanpython lecture" --keyword "lecture,python" --content "Diego gave a great talk"
./na find --keyword "lecture"
./na find # shows all
./na add  # prompts for info
'''

from naclass import na
import argparse
import sys

parser = argparse.ArgumentParser()
parser.add_argument('action', choices=['add', 'find'])
parser.add_argument('--json', type=str, help="file containing JSON-formatted 'title', 'content' and 'keyword'")
parser.add_argument("--title", type=str, default="", help="title (short)")
parser.add_argument("--keywords", type=str, default="", help="comma-separated keywords")
parser.add_argument("--content", type=str, default="", help="content (long; markdown format)")
parser.add_argument("--debug", action="store_true", dest="debug", default=False, help="set debugging on")
parser.add_argument("--privacy", type=int, default=0, help="set privacy level (0=open, 1=closed)")
args = parser.parse_args()

args.keywords = args.keywords.split(',')

na = na(debug=args.debug)

if args.json:
    import json
    for line in open(args.json, "r"):
        if (len(line)) > 1:
            try:
                json = json.loads(line)
            except:
                pass
            if 'title' not in json:
                sys.exit(1)
            if 'content' not in json:
                json['content'] = ""
            if 'keyword' in json:
                keyword = json['keyword'].split(',')
            else:
                keyword = ''
            if 'privacy' not in json:
                json['privacy'] = 0
            json['keyword'].split(',')
            id = na.add(title=json['title'], keywords=keyword, content=json['content'], privacy=json['privacy'])
    sys.exit(0)

if args.title:
    if args.action != "add":
        print "warning: --title is ignored unless --action!='add'"
    title = args.title
else:
    title = ""
if args.content:
    if args.action != "add":
        print "warning: --content is ignored unless --action='add'"
    content = args.content
else:
    content = ""

if args.action == "add":
    if args.title == "" and args.content == "":
        keyword_list = na.sql("SELECT keywordId, keyword FROM keyword;")
        msg = "Keywords (e.g. one of following) "
        for key in keyword_list:
            msg = msg + key[1] + ","
        msg = msg + "... : "
        keywords = raw_input(msg).split(',')
        title = raw_input("Title: ")
        content = raw_input("Content: ")
        privacy = raw_input("Privacy (numeric): ")
        privacy = int(privacy)
        id = na.add(title=title, keywords=keywords, content=content, privacy=privacy)
    else:
        id = na.add(title=args.title, keywords=args.keywords, content=args.content, privacy=args.privacy)

if args.action == "find":
    if args.keywords[0] != '':
        na.find(keywords=args.keywords)
    else:
        na.find(keywords='?'.split(','))


