#!/usr/bin/python

'''
./na --action add --title "oceanpython lecture" --keyword "lecture,python" --content "Diego gave a great talk"
./na --action find --keyword "lecture"
'''

from naclass import na
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--action', type=str, help="action ('add' or 'find')", choices=['add', 'find'])
parser.add_argument("--title", type=str, help="title (short)")
parser.add_argument("--keyword", type=str, help="comma-separated keywords")
parser.add_argument("--content", type=str, help="content (long; markdown format)")
parser.add_argument("--debug", action="store_true", dest="debug", default=False, help="set debugging on")
args = parser.parse_args()

if args.keyword:
    if args.action=="add":
        keywords = args.keyword.split(',')
    else:
        keywords = args.keyword.split(',') # FIXME: allow also |
if args.title:
    if args.action != "add":
        print "warning: --title is ignored unless --action!='add'"
    title = args.title
else:
    title = ""
if args.content:
    if args.action != "add":
        print "warning: --content is ignored unless --action='add'"
    content = args.content
else:
    content = ""

na = na(debug=args.debug)
if args.action == "add":
    na.add(title, keywords, content)

if args.action == "find":
    na.find(keywords)

